### ISSUE TITLE
When running grf-main, max_spacer_len and max_tr parameters cause error

### ISSUE THREAD

**Issue by Pushya-Krishna** [bioinfolabmu/GenericRepeatFinder#1]
I have installed the Generic Repeat Finder, however when I try to run the grf-main command and include the parameters for max_spacer_len and max_tr, I receive the following error: 

sh: 1: ./grf-filter: not found
failed to execute command ./grf-filter 5 10 0 100 testgrf/perfect.fasta testgrf/perfect.fasta.filterd

When I go to the src/grf-filter folder, ./grf-filter works fine and when I remove those two parameters from my command, it runs properly. Here is my original command:

grf-main -i testgrf.fasta -c 0 -o testgrf --min_tr 5 --max_mismatch 5 --max_indel 50 -p 20 -s 5 --min_space 0 --max_space 200 --max_tr 30 --min_spacer_len 0 --max_spacer_len 200

I tried including the src/grf-filter to my path variable however it did not change anything and I received the same error.
Does anyone have any suggestions?

**Comment by sjm888888** [comment]
It's designed to run everything from "bin/" folder. The code assume "grf-filter" and "grf-main" are in the same directory (i.e., "bin/").
The work around is to put "grf-filter" and "grf-main" in the same folder.

**Comment by sjm888888** [comment]
> I have installed the Generic Repeat Finder, however when I try to run the grf-main command and include the parameters for max_spacer_len and max_tr, I receive the following error:
> 
> sh: 1: ./grf-filter: not found
> failed to execute command ./grf-filter 5 10 0 100 testgrf/perfect.fasta testgrf/perfect.fasta.filterd
> 
> When I go to the src/grf-filter folder, ./grf-filter works fine and when I remove those two parameters from my command, it runs properly. Here is my original command:
> 
> grf-main -i testgrf.fasta -c 0 -o testgrf --min_tr 5 --max_mismatch 5 --max_indel 50 -p 20 -s 5 --min_space 0 --max_space 200 --max_tr 30 --min_spacer_len 0 --max_spacer_len 200
> 
> I tried including the src/grf-filter to my path variable however it did not change anything and I received the same error.
> Does anyone have any suggestions?

It's designed to run everything from "bin/" folder. The code assume "grf-filter" and "grf-main" are in the same directory (i.e., "bin/").
The work around is to put "grf-filter" and "grf-main" in the same folder.

**Comment by Pushya-Krishna** [comment]
I have tried that and it doesn't seem to be working given that I have received the same error again. Would there be an issue if I am using a linux subsystem?

**Comment by Pushya-Krishna** [comment]
Actually I am experiencing another issue, when I try to run the grf-filter command by itself i receive the following error:

grf-filter 5 30 0 200 testgrf.fasta testgrffilter.fasta
Segmentation fault (core dumped)


Any suggestions? Sorry for all of the comments, I am pretty new to this. Thanks

**Comment by sjm888888** [comment]
(1) Do you mean Linux subsystem in Windows? I have never tested the program in such system. Could be the problem of it.
(2) core dumped ... Can you show me some samples of your input fasta file? Could be the format problem.

**Comment by Pushya-Krishna** [comment]
1). Yes I am using the linux subsystem in Windows (Ubuntu specficially)
2). My fasta file looks like this: 

>seq1
GACCCTTTTTTAAAAAAGAGGG
>seq2
GACCCTTTTTTCAAAAAAGAGGG
>seq3
GACCCTTTTTTCCCCCAAAAAAGAGGG
>seq4
GACCCTTTTTTCGGACGATTTCTTACGCCCTTATAAATCAGCAAGTTACGAGACCTCGAAAAAAGAGGG
>seq5
CCATCAAAAGACCTTTCGCGCCCGAACGGCACGGTTGATCGCCGTCCCGGTCCTCGCGAAACGGCCGCCAATTGCCCGAAGCTTCCGACCCTTTTTTCGGACGATTTCTTACGCCCTTATAAATCAGCAAGTTACGAGACCTCGAAAAAAGAGGGTTTCTGGCGGGAAAAACTCGGTATTTCTTTTTCCTTCAAATGGTTATAGGTTTTCGGAGCTAGTTCACTGCCGTGTAGGCAGCTAAGAAAATCAGCCGGACGTTGTAGTAGTCGAGCGCGGTGTTC

**Comment by Pushya-Krishna** [comment]
There should be > in front of each seqx label

**Comment by sjm888888** [comment]
The input of grf-filter needs to have special sequence descriptions. Generic fasta file won't work.

Originally, it is used to filter the results generated by grf-main. The pipe line is grf-main->grf-filter.
But one reviewer ask me to put the filtration step inside grf-main ... Then I have add the step (i.e., calling grf-filter) inside grf-main.

Anyway, you need the output of grf-main as the input for grf-filter. 
In fact, you can avoid calling grf-filter in grf-main by removing these options from grf-main command line args:

"To restrict terminal repeat (TR) and spacer length of detected TIRs, TDRs, and MITE candidates, set the following options:\n"
            "Note: minimum TR length has been set in the mandatory parameter '--min_tr'.\n"
            "--max_tr <int>  Maximum TR length.\n"
            "--min_spacer_len <int>  Minimum spacer length.\n"
            "--max_spacer_len <int>  Maximum spacer length.\n"

**Comment by Pushya-Krishna** [comment]
Thank you so much! I used the grf-main output for the grf-filter input and it worked well. Thank you for helping me out, I greatly appreciate it.
