### ISSUE TITLE
Conda version available?

### ISSUE THREAD

**Issue by oushujun** [bioinfolabmu/GenericRepeatFinder#2]
Hello, 

Thanks for developing GRF! Just wondering, is that a conda version available? Some dependencies especially the gcc version is difficult to install. Thanks!

Best,
Shujun

**Comment by sjm888888** [comment]
Sorry. We don’t have a conda version.

**Comment by oushujun** [comment]
Thanks for your prompt reply. Is it possible for you to make one?

**Comment by sjm888888** [comment]
Sorry, I have limited knowledge of conda... can’t help you with it.
You can compile GCC from source and install it to your local folder if you can’t install it system wide.

**Comment by Juke34** [comment]
I wrote the conda recipe: [https://github.com/bioconda/bioconda-recipes/pull/19841#event-2965237999](https://github.com/bioconda/bioconda-recipes/pull/19841#event-2965237999).
It is now in Bioconda

**Comment by oushujun** [comment]
https://anaconda.org/bioconda/genericrepeatfinder
