### ISSUE TITLE
installation/compilation issue 

### ISSUE THREAD

**Issue by bioteksampath** [bioinfolabmu/GenericRepeatFinder#3]
Hi,
Thanks for developing GRF, Seems very interesting and useful.

when I try to install the program i'm getting an error by both installation methods,
wonder could plz help to overcome this...

---------------Method 1-----------------
[perumals@biocluster src]$ make
g++ -Wall -std=c++11 -O3 -fopenmp -Igrf-main -Igrf-intersperse -Igrf-mite-cluster -c grf-nest/main.cpp -o grf-nest/main.o
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
.
.
.

grf-nest/main.cpp:100:74: note:   no known conversion for argument 1 from ‘const std::tuple<unsigned int, unsigned int, unsigned int, unsigned int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ to ‘std::tuple<unsigned int, unsigned int, unsigned int, unsigned int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >&’
**make: *** [grf-nest/main.o] Error 1**
[perumals@biocluster src]$ cd grf-main/

---------------Method 2-----------------

[perumals@biocluster grf-main]$ g++ main.cpp DetectMITE.h DetectMITE.cpp DetectIR.h DetectIR.cpp functions.h functions.cpp -std=c++11 -fopenmp -O3 -o grf-main
/scratch/ccY0mTWI.o: In function `main':
main.cpp:(.text.startup+0x37c): undefined reference to `DetectDR::DetectDR(parameter)'
main.cpp:(.text.startup+0x39d): undefined reference to `vtable for DetectDR'
main.cpp:(.text.startup+0x425): undefined reference to `vtable for DetectDR'
**collect2: error: ld returned 1 exit status**
[perumals@biocluster grf-main]$

Thanks a lot, 
sam

**Comment by sjm888888** [comment]
Hi,
Looks like your g++ version is 4.8, but grf requires g++ version 4.9+.
Here are the instructions in the readme file to update your g++:

[2.2] g++ and gcc (version 4.9+)

Below is the commands to install version 4.9:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update; sudo apt-get install gcc-4.9 g++-4.9
sudo update-alternatives --remove-all gcc
sudo update-alternatives --remove-all g++
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
gcc -v
g++ -v

**Comment by sunnycqcn** [comment]
Hi,
I met the same issue. Although I know I can solve this issue by updating gcc and g++, it is very difficult that I do not have the root right. I am requiring our sys-admin help me update gcc and g++. I think it should be much better if you can change the code which can be installed under conda or non-root method.
Thanks,

**Comment by sjm888888** [comment]
Alternatively, you can download GCC source code, build, and install it to a local directory:
https://gcc.gnu.org/install
Then you can add it to your $PATH and use the alternative version of GCC instead of the system one.

**Comment by sunnycqcn** [comment]
Thanks,
I will try.
Fuyou
