### ISSUE TITLE
Can we cut genome into pieces and then run grf parallelizing?

### ISSUE THREAD

**Issue by xiekunwhy** [bioinfolabmu/GenericRepeatFinder#5]
Hi,

I want to cut whole genome into pieces (~5Mb per piece) and then run grf to get mite results, can I do that, why or why not?

Best,
Kun

**Comment by sjm888888** [comment]
Yes, you can do that (just make sure you split genome to valid FASTA files). You can also specify -t <num_of_threads> in grf-main to run it in parallel. 
If you want to cut genome to pieces, please read section [3.3.2] Different steps in MITE detection in the readme.txt. You can run grf-main in different processes for your split genome files to find the MITE candidates, but when you do the CD-HIT step to cluster similar MITE sequences, you have to combine all the candidate sequences to a single FASTA file and use it as input for CD-HIT.
Another thing to notice is that, if a MITE candidate is cross the 5Mb boundary of your cut, it won't be detected.

**Comment by xiekunwhy** [comment]
Thank you for your reply, and I will try to cut large genome into pieces and run grf-main in parallel, than combine results.

Best,
Kun
