### ISSUE TITLE
Is there a command line to detect non-LTR only using GRF?

### ISSUE THREAD

**Issue by xiekunwhy** [bioinfolabmu/GenericRepeatFinder#6]
Hi,

Is there a command line to detect non-LTR only using GenericRepeatFinder, or how to use it to detect and characterize non-LTR elements?

Best,
Kun

**Comment by xiekunwhy** [comment]
I found grf-intersperse.

**Comment by sjm888888** [comment]
Yes, grf-intersperse can be used to detect interspersed repeats.

**Comment by xiekunwhy** [comment]
Hi,
Can I also cut genomes into pieces to run grf-intersperse, like mite(https://github.com/bioinfolabmu/GenericRepeatFinder/issues/5)?
Best,
Kun

**Comment by sjm888888** [comment]
Please refer to section [3.3.2] Different steps in MITE detection in the readme.txt. You can cut genomes into pieces and then run grf-main with options for MITE detection, use CD-HIT to cluster similar MITE sequences, and use "grf-mite-cluster" to filter results generated from "cd-hit-est"
